# makefile for main using LinkedStack
main.exe: main.o 
	g++ -std=gnu++11 -o main.exe main.o 
main.o: main.cpp LinkedStack.cpp LinkedStack.h StackInterface.h Node.h Node.cpp
	g++ -std=gnu++11 -g -c main.cpp

	
	
	