# makefile for BagTester using LinkedBag
BagTester.exe: BagTester.o 
	g++ -std=gnu++11 -o BagTester.exe BagTester.o 
BagTester.o: BagTester.cpp LinkedBag.cpp LinkedBag.h BagInterface.h
	g++ -std=gnu++11 -g -c BagTester.cpp


	
	
	