# makefile for main using LinkedBag or ArrayBag
main.exe: main.o 
	g++ -std=gnu++11 -o main.exe main.o 
main.o: main.cpp LinkedBag.cpp LinkedBag.h BagInterface.h ArrayBag.h ArrayBag.cpp 
	g++ -std=gnu++11 -g -c main.cpp

	
	
	